version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - NODE_ENV=production
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    environment:
      - PORT=3001
      - NODE_ENV=production
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL:-http://backend:3000}
    ports:
      - "3001:3001"
    depends_on:
      - backend 