[build]
builder = "nixpacks"
buildCommand = "cd ../.. && bun run build:api && cd packages/web && bun run build"

[deploy]
startCommand = "bun run start"
healthcheckPath = "/"
restartPolicyType = "on_failure"

[variables]
NODE_ENV = "production"
