[build]
builder = "nixpacks"

[variables]
BUN_VERSION = "1.0.20"
NODE_ENV = "production"
PORT = "3000"
# The backend URL that Next.js will use for rewrites
NEXT_PUBLIC_BACKEND_URL = "${{prophesy-backend.RAILWAY_PRIVATE_DOMAIN}}"

[phases.setup]
nixPkgs = ["bun"]
cmds = ["echo 'Setting up Bun'"]

[phases.install]
cmds = ["bun install --frozen-lockfile"]
dependsOn = ["setup"]

[phases.build]
cmds = ["echo 'Starting build' && bun run build && echo 'Build complete'"]
dependsOn = ["install"]

[start]
cmd = "bun run start"
dependsOn = ["build"]
