[build]
builder = "nixpacks"

[variables]
BUN_VERSION = "1.0.20"
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["bun"]

[phases.install]
cmds = ["bun install"]

[phases.build]
cmds = ["bun run build"]

[start]
cmd = "bun run start"
